# SPDX-FileCopyrightText: 2023 Dyne.org foundation
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Install the inbox service
  hosts: all
  remote_user: root
  roles:
    - common
    - proxy-docker-compose

