---
- name: Create non root user
  hosts: all
  remote_user: root
  tasks:
  - name: Add the user 'proxy'
    ansible.builtin.user:
      name: proxy
      shell: /bin/bash
  - name: Create .ssh directory
    file:
      path: /home/proxy/.ssh
      state: directory
      owner: proxy
      group: proxy
  - name: Set authorized keys for user controller
    copy:
      src: /root/.ssh/authorized_keys
      remote_src: true
      dest: /home/controller/.ssh/authorized_keys
      owner: controller
      group: controller
- name: Install zenflows proxy
  hosts: all
  remote_user: root
  become_user: proxy
  become_method: su
  vars:
    basedir: "/interfacer-proxy"
  tasks:
  - name: Install package dependencies
    ansible.builtin.package:
      name:
       - nginx
       - tmux
      state: latest
  - name: Build app
    command: make
    args:
      chdir: ..
    delegate_to: localhost

  - name: Create project directory
    ansible.builtin.file:
      path: "/{{ basedir }}"
      state: directory

  - name: copy executable
    copy:
      dest: "{{ basedir }}/interfacer-gateway"
      src: "../interfacer-gateway"
      owner: proxy
      group: proxy

  - name: Make service executable
    file: dest="{{ basedir }}/interfacer-gateway" mode=a+x

  - name: kill old tmux session
    command: tmux kill-session -t zenflows-proxy-{{ port }}
    ignore_errors: yes

  - name: .env
    blockinfile:
      dest: "/{{ basedir }}/.env.{{ port }}"
      create: true
      block: |
        export ZENFLOWS={{ zenflows }}
        export HERE_API={{ here_api }}
        export PORT={{ port }}
        export INBOX={{ inbox }}

  - name: run proxy
    # become: true
    command: tmux new-session -d -s zenflows-proxy-{{ port }} "source {{ basedir }}/.env.{{ port }} && {{ basedir }}/interfacer-gateway"

  - name: Nginx service
    blockinfile:
      dest: "/etc/nginx/conf.d/{{ domain_name }}.conf"
      create: true
      block: |
        # server {
        # listen 80 default_server;
        #
        # server_name {{ domain_name }};
        #
        # return 301 https://$host$request_uri;
        # }
        server {
          listen 443 ssl;
          root /var/www/html;
          server_name {{ domain_name }};
          ssl_certificate /etc/letsencrypt/live/{{ domain_name}}/fullchain.pem;
          ssl_certificate_key /etc/letsencrypt/live/{{ domain_name}}/privkey.pem;
          include /etc/letsencrypt/options-ssl-nginx.conf; # Redirect non-https traffic to https
          if ($scheme != "https") {
              return 301 https://$host$request_uri;
          }
          location / {
            proxy_pass http://127.0.0.1:{{ port }}/;
          }
        }

  - name: Remove default config for nginx
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent

  - name: Restart nginx
    ansible.builtin.service:
      state: reloaded
      name: nginx
